### ISSUE TITLE
Roadmap for release

### ISSUE THREAD

**Issue by Syrcan** [GregTechCEu/GregTech-Community-Pack#14]
I will add or remove things as progress is done.

**Important:**
- All tasks done

**Optional:**
- Enchanted Books (we have xp bottles now, so maybe not?)
- Synthetic Leather (?)
- Brewing Stand gregified recipe (?)
- Update random mods

**Comment by Syrcan** [comment]
I did minor updates to your comment to track progress.

**Comment by TechLord22** [comment]
6 Jan 2022
incomplete quests 

- [ ] 102 cells (mention steel cell)
- [ ] 104 LV-tier AE2 (mention to use GT Fluix Crystal over AE2)
- [ ] 225 autocrafting
- [ ] 229, 231 HV fuels
- [ ] 246 AE2 (low prio)
missing quests
- [ ] fluid regulators
- [ ] jetpack and armor quests
- [ ] units overview
  - [ ] RF lore
- [ ] world accelerator (put in IV)
- [ ] item pipe priority behaviour
- [ ] shift mouse2 on multiblock controllers to preview
- [ ] voiding cover
- [ ] packager
- [ ] fisher (hide in mechanics, dont add to LV)
- [ ] item collector (same)
- [ ] diode (same)
- [ ] rock breaker (same)
- [ ] turbo charger (same)

misc quest tasks:
- [ ] improve enet quests
  - [ ] explain gt6 cable style
- [ ] add loose progression to EV-UV
- [ ] clean up LV tab a bit (if possible)

CT tasks
- [ ] balance AE2 fluid storage
- [ ] some better solution for early game item storage (I noticed this was a common gripe)
- [ ] Nether Star recipe
- [ ] XP recipe
- [ ] enchanted books recipe (low prio)
- [ ] dan mode (low prio)

other tasks
- [ ] fix BQ party crash
- [ ] right click get crops 1.12
- [ ] update pae2
